# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-10 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20171208_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='my_date_field',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
